definitions:
  handler.PingServerResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.PingResponse'
      message:
        type: string
    type: object
  schemas.PingResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Ping the server to check if it is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.PingServerResponse'
      summary: Ping the server
      tags:
      - Ping
swagger: "2.0"
